[package]
name = "migrateable_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[features]
default = ["hashed"]
hashed = []
fjall = []
__lock_discover = []

[dependencies]
syn = { version = "2.0", features = ["derive", "parsing", "printing"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-crate = "3.5"
strum = "0.28.0"
strum_macros = "0.28.0"
convert_case = "0.11"
